# Generated by Django 3.2.25 on 2025-04-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0033_auto_20231108_1355'),
        ('payment', '0041_auto_20210623_1545'),
    ]

    operations = [
    ]
