# Generated by Django 3.2.25 on 2025-04-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0014_basket_authorization_code'),
        ('basket', '0017_alter_lineattribute_value'),
    ]

    operations = [
    ]
