name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Pull submodules
        run: git submodule update --init --recursive

      - name: Build Docker image
        run: docker build . --file .github/Dockerfile --tag eoluchile/ecommerce-koa:${GITHUB_SHA} --tag eoluchile/ecommerce-koa:latest

      - name: Run tests
        run: docker run eoluchile/ecommerce-koa:${GITHUB_SHA} /openedx/ecommerce/tests.sh

      - name: Push
        run: |
          echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin
          docker push eoluchile/ecommerce-koa:${GITHUB_SHA}
          docker push eoluchile/ecommerce-koa:latest
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}